name: flutter_mvp
description: A minimal Flutter MVP that reproduces the provided UI mock (Spanish labels).
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.2
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
