name: flutter_mvp
description: A minimal Flutter MVP that reproduces the provided UI mock (Spanish labels).
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
